// <auto-generated />
namespace OpenOrderFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(data));
        
        string IMigrationMetadata.Id
        {
            get { return "201405311730073_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
